version: '3.9'

services:
  #new service (java_app)
  java_app:
    container_name: java_app
    image: aidyn.ibragimov/java_app:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://172.17.0.1:5432/javadocker
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - SPRING_LIQUIBASE_CHANGELOG=classpath:/db/changelog/db.changelog-master.xml
    depends_on:
      - java_db

  #old service (postgres)
  java_db:
    container_name: java_db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: javadocker

    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}